---
abstract: 'An apt-like Github clone utility.'
author:
  - 'Cornelius, C<< <cornelius.howl at gmail.com> >>'
  - 'Cornelius <cornelius.howl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-gh
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  File::Temp: 0
  JSON: 0
  JSON::XS: 0
  LWP::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
