---
abstract: 'An apt-like Github utility.'
author:
  - 'Cornelius, C<< <cornelius.howl at gmail.com> >>'
  - 'Cornelius <cornelius.howl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-gh
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::CLI: 0
  Exporter::Lite: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  HTML::Strip: 0
  IO::Pager: 0
  JSON: 0
  JSON::XS: 0
  LWP::Simple: 0
  Text::Wrap: 0
  URI: 0
  XML::Atom::Feed: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/c9s/App-gh
version: 0.21
